// catBreeds.js
const catBreeds = [
  { value: "Abyssinian", label: "Abyssinian" },
  { value: "American Bobtail", label: "American Bobtail" },
  { value: "American Curl", label: "American Curl" },
  { value: "American Shorthair", label: "American Shorthair" },
  { value: "American Wirehair", label: "American Wirehair" },
  { value: "Balinese", label: "Balinese" },
  { value: "Bengal", label: "Bengal" },
  { value: "Birman", label: "Birman" },
  { value: "Bombay", label: "Bombay" },
  { value: "British Shorthair", label: "British Shorthair" },
  { value: "Burmese", label: "Burmese" },
  { value: "Burmilla", label: "Burmilla" },
  { value: "Chartreux", label: "Chartreux" },
  { value: "Cornish Rex", label: "Cornish Rex" },
  { value: "Devon Rex", label: "Devon Rex" },
  { value: "Egyptian Mau", label: "Egyptian Mau" },
  { value: "European Burmese", label: "European Burmese" },
  { value: "Exotic Shorthair", label: "Exotic Shorthair" },
  { value: "Havana Brown", label: "Havana Brown" },
  { value: "Himalayan", label: "Himalayan" },
  { value: "Japanese Bobtail", label: "Japanese Bobtail" },
  { value: "Khao Manee", label: "Khao Manee" },
  { value: "Korat", label: "Korat" },
  { value: "LaPerm", label: "LaPerm" },
  { value: "Maine Coon", label: "Maine Coon" },
  { value: "Manx", label: "Manx" },
  { value: "Norwegian Forest Cat", label: "Norwegian Forest Cat" },
  { value: "Ocicat", label: "Ocicat" },
  { value: "Oriental", label: "Oriental" },
  { value: "Persian", label: "Persian" },
  { value: "Ragdoll", label: "Ragdoll" },
  { value: "Russian Blue", label: "Russian Blue" },
  { value: "Scottish Fold", label: "Scottish Fold" },
  { value: "Selkirk Rex", label: "Selkirk Rex" },
  { value: "Siamese", label: "Siamese" },
  { value: "Siberian", label: "Siberian" },
  { value: "Singapura", label: "Singapura" },
  { value: "Snowshoe", label: "Snowshoe" },
  { value: "Somali", label: "Somali" },
  { value: "Sphynx", label: "Sphynx" },
  { value: "Tonkinese", label: "Tonkinese" },
  { value: "Turkish Angora", label: "Turkish Angora" },
  { value: "Turkish Van", label: "Turkish Van" },
  { value: "Other", label: "Autre" },
  { value: "Unknown", label: "Inconnu" },
  // Add more breeds as needed
];


export default catBreeds;
